### ISSUE TITLE
Update Readme documentation

### ISSUE THREAD

**Issue by AntoninMarchardDev** [eversign/eversign-node-sdk#12]
I tried to use your node JS SDK, that is very useful, however, there are some mistakes in the Github documentation.

- You should specify class requirements, for example, that we need to `require/import` Signer, Recipient, or Template.

- `DocumentTemplate` doesn't exists anymore in your lib, so update documentation for `Template`.

- `new Client("MY_HASH", 12345678);` is not clear. params should be `API_KEY` and `BUSINESS_ID`. `MY_HASH` is not clear and the numbers after too. 

I should create a PR if needed,

Thank you for the lib

**Comment by dominikkukacka** [comment]
A PR would be greatly appreciated! :)

**Comment by AntoninMarchardDev** [comment]
@dominikkukacka I think we can close this issue :) #13
