### ISSUE TITLE
Signer object misses a few fields for the UseTemplate use case

### ISSUE THREAD

**Issue by gtron** [eversign/eversign-node-sdk#59]
Hello, 

The current implementation of the Signer object doesn't give access to these fields defined in the API for the UseTemplate use case: 

- deliver_email
- signer_authentication_sms_enabled
- signer_authentication_phone_number
- message
- language

API Definition: https://eversign.com/api/documentation/methods#use-template
![image](https://user-images.githubusercontent.com/6774022/138554771-e89d77bb-293d-4777-bbaf-834518a6f726.png)

**Comment by milanlatinovic** [comment]
Hi @gtron,

Thank you for reporting this. I have extended Signer object with missing fields.
Let me know if you recognize anything else.

Updates are available within 1.9.3 release.

All the best!
